// <auto-generated />
using DapperDemo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DapperDemo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260303235459_SeedCompanyData")]
    partial class SeedCompanyData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DapperDemo.Models.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompanyId");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            CompanyId = 1,
                            Address = "1 Acme Way",
                            City = "Metropolis",
                            Name = "Acme Corp",
                            PostalCode = "90001",
                            State = "CA"
                        },
                        new
                        {
                            CompanyId = 2,
                            Address = "42 Contoso Blvd",
                            City = "Redmond",
                            Name = "Contoso Ltd",
                            PostalCode = "98052",
                            State = "WA"
                        },
                        new
                        {
                            CompanyId = 3,
                            Address = "500 Main St",
                            City = "Seattle",
                            Name = "Fabrikam",
                            PostalCode = "98101",
                            State = "WA"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
